### ISSUE TITLE
FIX BUG: `Terrain mesh is randomly broken because of brick's top face`

### ISSUE THREAD

**Issue by stone-SJH** [tetreum/brickcraft#3]
PR: https://github.com/tetreum/brickcraft/pull/2

In the `WorldGenerationTest.unity` scene, you're generating some huge mesh without setting `Mesh.indexFormat` to `UInt32`(the default value is UInt16), which causing meshes with vertex count > 65535 fail to render normally. 
Unity doc here: https://docs.unity3d.com/ScriptReference/Mesh-indexFormat.html

However, using UInt32 indices format instead of UInt16 will probably drop performance and need more memory (for example, X-5 Z-3 ChunkSlice#4, which has 101920 verts and 221400 triangles, cost around 6.5MB for indices using UInt32 or around 1.5MB using UInt16). So a better solution might be split your huge meshes into sub-meshes(verts < 65535) and still using UInt16, if you have time, you can have a try about this :)

**Comment by tetreum** [comment]
Funny because you can see here https://github.com/tetreum/brickcraft/blob/60e23c0c5544586e7d3b7a90cd27f617a21ab556/Assets/Scripts/World/WorldBehaviour.cs#L179 that is something that i already did when i was bruteforcing the entire brick model rather than the shown faces xDD And then i never thought of it again xDDD
The thing is, i belive it throwed me an error back then. Why isn't it doing the same in those cases?

**Comment by tetreum** [comment]
I've added you to https://github.com/tetreum/brickcraft#credits and also on https://tetreum.github.io/brickcraft/?/help
Thank you so much!
